export const doctorsList = [
  {
    id: 1,
    name: "Dr. Aisha Abdullah",
    photo: "/images/dr_aisha.jpg",
    specialties: ["Cardiologist", "Internal Medicine"],
    appointmentDays: ["Monday", "Wednesday", "Friday"],
    clinicTiming: "9:00 AM - 5:00 PM",
    hospitals: ["City Heart Center", "General Hospital", "Metropolitan Health Institute"],
    degrees: ["MD", "Ph.D. in Cardiovascular Science"],
    yearsOfExperience: 15,
    successfulOperations: 500,
    additionalDetails: "Expert in interventional cardiology and heart failure management.",
    phone: "+1 (555) 101-2345",
    email: "aisha.abdullah@example.com",
    website: "www.draishaabdullah.com",
    consultationFee: "$200"
  },
  {
    id: 2,
    name: "Dr. Ahmed Malik",
    photo: "/images/dr_ahmed.jpg",
    specialties: ["Dermatologist", "Cosmetologist"],
    appointmentDays: ["Tuesday", "Thursday", "Saturday"],
    clinicTiming: "10:00 AM - 4:00 PM",
    hospitals: ["SkinCare Hospital", "City Clinic", "Dermatology Specialists Center"],
    degrees: ["MBBS", "Diploma in Dermatology"],
    yearsOfExperience: 10,
    successfulOperations: 300,
    additionalDetails: "Specializes in skin conditions and cosmetic procedures.",
    phone: "+1 (555) 202-3456",
    email: "ahmed.malik@example.com",
    website: "www.drahmedmalik.com",
    consultationFee: "$150"
  },
  {
    id: 3,
    name: "Dr. Fatima Rahman",
    photo: "/images/dr_fatima.jpg",
    specialties: ["Pediatrician", "Neonatologist"],
    appointmentDays: ["Monday", "Thursday", "Saturday"],
    clinicTiming: "8:00 AM - 2:00 PM",
    hospitals: ["Happy Kids Clinic", "City General Hospital", "Pediatric Health Center"],
    degrees: ["MBBS", "Fellowship in Neonatology"],
    yearsOfExperience: 8,
    successfulOperations: 200,
    additionalDetails: "Focuses on newborn care and pediatric health.",
    phone: "+1 (555) 303-4567",
    email: "fatima.rahman@example.com",
    website: "www.drfatimarahman.com",
    consultationFee: "$180"
  },
  {
    id: 4,
    name: "Dr. Ali Hussain",
    photo: "/images/dr_ali.jpg",
    specialties: ["Orthopedic Surgeon", "Sports Medicine"],
    appointmentDays: ["Tuesday", "Friday", "Sunday"],
    clinicTiming: "11:00 AM - 6:00 PM",
    hospitals: ["OrthoCare Hospital", "Sports Medicine Clinic", "Joint Replacement Center"],
    degrees: ["MS Orthopedics", "Sports Medicine Certification"],
    yearsOfExperience: 20,
    successfulOperations: 700,
    additionalDetails: "Renowned for joint replacement surgeries and sports injury treatments.",
    phone: "+1 (555) 404-5678",
    email: "ali.hussain@example.com",
    website: "www.draliHussain.com",
    consultationFee: "$250"
  },
  {
    id: 5,
    name: "Dr. Layla Khan",
    photo: "/images/dr_layla.jpg",
    specialties: ["Neurologist", "Neurophysiologist"],
    appointmentDays: ["Monday", "Wednesday", "Saturday"],
    clinicTiming: "9:00 AM - 3:00 PM",
    hospitals: ["Neuro Health Center", "General Hospital", "Advanced Neuro Institute"],
    degrees: ["MD Neurology", "Ph.D. in Neuroscience"],
    yearsOfExperience: 12,
    successfulOperations: 250,
    additionalDetails: "Expert in treating epilepsy and neurodegenerative disorders.",
    phone: "+1 (555) 505-6789",
    email: "layla.khan@example.com",
    website: "www.drlaylakhan.com",
    consultationFee: "$220"
  },
  {
    id: 6,
    name: "Dr. Yusuf Ahmed",
    photo: "/images/dr_yusuf.jpg",
    specialties: ["General Practitioner", "Family Medicine"],
    appointmentDays: ["Tuesday", "Thursday", "Saturday"],
    clinicTiming: "8:00 AM - 1:00 PM",
    hospitals: ["City General Hospital", "Community Health Center", "Primary Care Clinic"],
    degrees: ["MBBS", "Diploma in Family Medicine"],
    yearsOfExperience: 18,
    successfulOperations: 150,
    additionalDetails: "Provides comprehensive primary care and family health services.",
    phone: "+1 (555) 606-7890",
    email: "yusuf.ahmed@example.com",
    website: "www.dryusufahmed.com",
    consultationFee: "$100"
  },
  {
    id: 7,
    name: "Dr. Maryam Akhtar",
    photo: "/images/dr_maryam.jpg",
    specialties: ["Gynecologist", "Obstetrician"],
    appointmentDays: ["Wednesday", "Friday", "Sunday"],
    clinicTiming: "10:00 AM - 5:00 PM",
    hospitals: ["Women's Health Clinic", "Maternity Care Center", "City Hospital"],
    degrees: ["MBBS", "MD Gynecology"],
    yearsOfExperience: 14,
    successfulOperations: 400,
    additionalDetails: "Specializes in women's reproductive health and prenatal care.",
    phone: "+1 (555) 707-8901",
    email: "maryam.akhtar@example.com",
    website: "www.drmaryamakhtar.com",
    consultationFee: "$180"
  },
  {
    id: 8,
    name: "Dr. Bilal Sheikh",
    photo: "/images/dr_bilal.jpg",
    specialties: ["Endocrinologist", "Diabetologist"],
    appointmentDays: ["Monday", "Thursday", "Friday"],
    clinicTiming: "9:00 AM - 4:00 PM",
    hospitals: ["EndoCare Center", "Diabetes Health Institute", "General Hospital"],
    degrees: ["MD Endocrinology", "Fellowship in Diabetes"],
    yearsOfExperience: 11,
    successfulOperations: 180,
    additionalDetails: "Expert in hormone-related disorders and diabetes management.",
    phone: "+1 (555) 808-9012",
    email: "bilal.sheikh@example.com",
    website: "www.drbilalsheikh.com",
    consultationFee: "$160"
  },
  {
    id: 9,
    name: "Dr. Zainab Jamil",
    photo: "/images/dr_zainab.jpg",
    specialties: ["Ophthalmologist", "Retina Specialist"],
    appointmentDays: ["Tuesday", "Thursday", "Saturday"],
    clinicTiming: "10:00 AM - 6:00 PM",
    hospitals: ["VisionCare Hospital", "Eye Health Center", "Advanced Eye Clinic"],
    degrees: ["MBBS", "MD Ophthalmology"],
    yearsOfExperience: 16,
    successfulOperations: 600,
    additionalDetails: "Specializes in eye surgeries and retinal treatments.",
    phone: "+1 (555) 909-0123",
    email: "zainab.jamil@example.com",
    website: "www.drzainabjamil.com",
    consultationFee: "$210"
  },
  {
    id: 10,
    name: "Dr. Ibrahim Saeed",
    photo: "/images/dr_ibrahim.jpg",
    specialties: ["Psychiatrist", "Psychotherapist"],
    appointmentDays: ["Monday", "Wednesday", "Friday"],
    clinicTiming: "11:00 AM - 5:00 PM",
    hospitals: ["Mental Health Clinic", "City Hospital", "Neuropsychiatric Center"],
    degrees: ["MD Psychiatry", "Diploma in Psychotherapy"],
    yearsOfExperience: 22,
    successfulOperations: 100,
    additionalDetails: "Focuses on mental health therapies and psychological counseling.",
    phone: "+1 (555) 010-1234",
    email: "ibrahim.saeed@example.com",
    website: "www.dribrahimsaeed.com",
    consultationFee: "$190"
  },
  {
    id: 11,
    name: "Dr. Sara Abbas",
    photo: "/images/dr_sara.jpg",
    specialties: ["Anesthesiologist", "Pain Management Specialist"],
    appointmentDays: ["Monday", "Wednesday", "Friday"],
    clinicTiming: "7:00 AM - 3:00 PM",
    hospitals: ["City Medical Center", "Pain Relief Clinic", "Anesthesia Care Hospital"],
    degrees: ["MD Anesthesiology", "Fellowship in Pain Management"],
    yearsOfExperience: 13,
    successfulOperations: 400,
    additionalDetails: "Expert in anesthesia and chronic pain management.",
    phone: "+1 (555) 111-2233",
    email: "sara.abbas@example.com",
    website: "www.drsaraabbas.com",
    consultationFee: "$180"
  },
  {
    id: 12,
    name: "Dr. Omar Nawaz",
    photo: "/images/dr_omar.jpg",
    specialties: ["Radiologist", "Oncologist"],
    appointmentDays: ["Tuesday", "Thursday", "Saturday"],
    clinicTiming: "9:00 AM - 2:00 PM",
    hospitals: ["City Cancer Center", "Radiology Health Institute", "General Hospital"],
    degrees: ["MD Radiology", "Fellowship in Oncology"],
    yearsOfExperience: 9,
    successfulOperations: 150,
    additionalDetails: "Specializes in imaging and cancer treatments.",
    phone: "+1 (555) 222-3344",
    email: "omar.nawaz@example.com",
    website: "www.dromarnawaz.com",
    consultationFee: "$230"
  }
];
